### ISSUE TITLE
Parameter to change endpoint to "*.ods.opinsights.azure.cn"

### ISSUE THREAD

**Issue by prankur003** [yokawasa/azure-log-analytics-data-collector-python#2]
For Client.py 
post_data method should have a parameter to change endpoint for other cloud like china has "*.ods.opinsights.azure.cn".

I can see the implementation is available for Ruby but not for Python.

**Comment by yokawasa** [comment]
@prankur003 

Thank you for the issue. 

I've published `azure-log-analytics-data-collector-api-0.4.0` that support endpoint param.
- https://pypi.org/project/azure-log-analytics-data-collector-api/

I'll close the issue. Let me know if you find any issue.
